packages:
  - backend
  - frontend
  - types

catalog:
  "@types/node": ^20.19.33
  oxlint: "^1.47.0"
  oxlint-tsgolint: "^0.12.1"
  typescript: ^5.9.3
  zod: ^4.3.6

lockfileIncludeTarballUrl: true

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
